### ISSUE TITLE
Version 1 Release

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#143]
What is required before version 1 can be released after which breaking changes should be kept to a minimum?

Blockers:
* [x] #132 / #118
* [x] decision about encoding #133
* [x] schema #129
* [x] error cleanup #183
* [x] decision about parsing more (or fewer) data types #136
* [x] really weird that pydantic doesn't support tuples even if no one wants to use them #12

To do on release:
* [x] change classifiers to stable
* [ ] add note to docs saying pydantic is stable, well tested and used in production on numerous projects (as it already is).
