### ISSUE TITLE
v1.7.3

### ISSUE THREAD

**Issue by PrettyWood** [samuelcolvin/pydantic#2158]
@samuelcolvin To help us track them all, here are the fixes that should/could be in a v1.7.3

- [x] fix: ignore `__doc__` as valid private attribute #2091
- [x] Fixes a regression where Enum fields would not propagate keyword arguments to the schema #2109
- [x] fix: update all modified field values in `root_validator` when `validate_assignment` is on #2119
- [x] fix: support `underscore_attrs_are_private` with generic models #2139 
- [x] fix: set right default value for required (optional) fields #2143
- [x] Fix #2111: support pickle for built-in dataclasses #2114
