### ISSUE TITLE
v1.9 is coming!

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#3537]
Hi all,

v1.9 is VERY overdue, but we're nearly there.

My plan before release:
* [x] merge any [open PRs with the "ready for review" label](https://github.com/samuelcolvin/pydantic/pulls?q=is%3Aopen+is%3Apr+label%3A%22ready+for+review%22) - currently there are 3, all basically ready to merge
* [x] create a pre-release `v1.9a1` and encourage people to test it before release - I guess I'll give people a week?
* [ ] test `v1.9a1` on projects where I use pydantic
* [ ] release **v1.9**

My aim is to get the new release out this year.

Are there any other PRs you really really want in this release? If so please comment below.

Similarly if you find a bug with this release, please create an issue and link to it here.

**Comment by layday** [comment]
These two typing issues would be good to resolve before release:

* https://github.com/samuelcolvin/pydantic/pull/3540
* https://github.com/samuelcolvin/pydantic/pull/2721/files#r771881485

#2650 is a breaking change and should probably be marked as such - custom encoders might not be equipped to handle `BaseModel`s.

**Comment by PrettyWood** [comment]
I reckon https://github.com/samuelcolvin/pydantic/pull/3201 and https://github.com/samuelcolvin/pydantic/pull/3182 are important to fix regressions

**Comment by samuelcolvin** [comment]
Thanks both. I'll look at these.

I meant to choose this to use the discussion which is linked from the release #3538.

I'll move you're comments across.

**Comment by samuelcolvin** [comment]
My mistake to create this, please use #3538 instead.
